name: Publish NPM

on:
  release:
    types: [published]
  # Atau bisa juga trigger otomatis saat push tag 'v*':
  # push:
  #   tags:
  #     - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Library
        run: npx ng build exp-shared-ui

      - name: Publish Package
        run: npm publish ./dist/exp-shared-ui --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
